config/routes.rb
Rails.application.routes.draw do
  resources :providers
  devise_for :users
  devise_for :installs
  
  resources :sales do
   member do  
      get :finish_sale
      get :cancel_sale
   end
  end 

  resources :parts
  root "homepage#index"

  resources :vehicles
  post "/vehicles/new" => "vehicles#create"

  resources :clients
  post "/clients/new" => "clients#create"

  resources :services do
    resources :tasks do
    end
  end

  resources :tasks do
    member do
      get :finish_task
    end
  end

  resources :services do
    member do
      get :finish_service
    end
  end

  resources :dashboards
  get "/dashboards/report/client" => "dashboards#client_report", as: "client_report"
  get "/dashboards/report/vehicle" => "dashboards#vehicle_report", as: "vehicle_report"
  get "/dashboards/report/service" => "dashboards#service_report", as: "service_report"
  get "/dashboards/report/sale" => "dashboards#sale_report", as: "sale_report"
  get "/dashboards/report/user" => "dashboards#user_report", as: "user_report"
  get "/dashboards/report/part" => "dashboards#part_report", as: "part_report"
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :tasks, dependent: :destroy
    has_one :sale
    belongs_to :vehicle
    
    validates :title, presence: true
    validates :value, presence: true
    validates :vehicle_id, presence: true

    scope :from_this_month, lambda { 
        where("services.created_at > ? AND services.created_at < ?", 
        Time.now.beginning_of_month, Time.now.end_of_month) }
    
    def get_tasks_on_time 
        @on_time = self.tasks.where("finish_date <= estimative")
    end

    def self.get_tasks_overdue
        @overdue = self.tasks.where("finish_date > estimative")
    end

    def count_tasks 
        self.tasks.count
    end

    def status_parsed
        if status == true 
            return "Concluida"
        else 
            return "Não concluida"
        end
    end

    def identification_string
        return "Servico ( ID: "+  self.id.to_s + " ) " + self.title
    end 

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def index 
        @services = Service.all.order('created_at DESC')
    end

    def show
        @service = Service.find(params[:id])
        @sale = @service.sale ||= nil 
        respond_to do |format|
            format.html
            format.pdf do
                render pdf: "Invoice No. ",
                page_size: 'A4',
                template: "services/pdf.html.erb",
                layout: "pdf.html.erb",
                orientation: "Landscape",
                lowquality: true,
                zoom: 1,
                dpi: 75
            end
        end
    end

    def new
        @services = Service.pluck(:title).sort
        @service = Service.new
        @vehicles = Vehicle.all
    end

    def create
        @service = Service.new(service_params)
    
        if @service.save
            redirect_to @service
        else
            redirect_to action: "new"
        end
        
    end

    def edit
        @service = Service.find(params[:id])
        @vehicles = Vehicle.all
    end

    def update
        @service = Service.find(params[:id])

        if @service.update(service_params)
            redirect_to @service
        else 
            redirect_to action: "edit"
        end

    end

    def destroy
        @service = Service.find(params[:id])
        @service.destroy
        
        redirect_to action: "index"
    end

    def finish_service
        @service = Service.find(params[:id])
        @service.update(status: true, finish_date: DateTime.now())
        flash[:notice] = "Serviço concluido!"
        redirect_to service_path(@service)
    end

    private
        def service_params
            params.require(:service).permit(:id, :title, :finish_date, :status, :estimative, :value, :vehicle_id)
        end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
       
        <%= form_with model: service do |form|%>            
            <div class="form-group pt-2">
                <%= form.label :title, value: "Titulo:" %> 
                <%= form.text_field :title, {id: "autocomplete12", class: "form-control", placeholder: "Digite o titulo do serviço"} %>
            </div>
             <div class="form-group pt-2">
                <%= form.label :estimative, value: "Estimativa:" %> 
                <%= form.date_field :estimative, {class: "form-control", placeholder: "Selecione uma estimativa para o serviço"} %>
            </div>
              <div class="form-group pt-2">
                <%= form.label :value, value: "Valor da mão de obra:" %> 
                 <%= form.number_field :value, {step: :any, class: "form-control", placeholder: "Insira o valor do serviço"} %>
            </div>
            <div class="form-group pt-2">
                <label for="vehicle_id"> Selecione o veiculo referente ao serviço </label> <br>
                <%= form.select :vehicle_id, @vehicles.collect{ |v| [v.model, v.id] }, {},  prompt: "Escolha um Veiculo", class: "form form-group form-control" %>
            </div>
            
            <div class="form-group pt-2">
                <%= form.label :status, value: "O serviço ja foi concluido?" %> 
                <%= form.check_box :status%>            
            </div>
            <div class="lead pt-5">
                <%= form.submit "Concluir", class: "btn btn-primary" %>
            </div>
         <% end %>
  
<%= form_tag(services_path, method: 'get', class: "form-inline") do %>
  <div id= "search-data" class="form-search search-data" data-skills="<%= @services.to_json %>">
  </div>
<% end %>

app/views/services/_service.html.erb
  <tr class="text-center">
            <th scope="row"></th>
            <td> <%= service.title %></td>
            <td> <%= service.estimative %></td>
            <td> <%= service.vehicle.model %> </td>
            <td> <%= service.vehicle.client.name %> </td>
            <td> <%= service.value %></td>
            <td> <%= service.sale ? service.sale.value + service.sale.comission_value : "Não possui" %> </td>
            <td> <%= service.sale ? service.sale.get_total_value : service.value %> </td>
            <td> <%= service.sale ? (link_to 'Ver', sale_path(service.sale)) : "Não possui" %>  </td>
            <td> <%= link_to ( service.sale ? sale_path(service.sale.id, format: :pdf) :
                                service_path(service, format: :pdf) ) do  %> 
                        <i class="bi bi-filetype-pdf " style="font-size: 20px"></i>
                    <% end %>  </td>
            <td> <%= link_to "Tarefas", service, class: "btn btn-md btn-primary my-2" %></td> 
            <td> <%= link_to "Deletar", service_path(service), class: "btn btn-md btn-danger my-2", 
                                                                      method: :delete, 
                                                                      data: { confirm: "Tem certeza que deseja deletar o serviço " + service.title + " ?"}  %> </td>
            <td> <%= link_to "Editar", edit_service_path(service), class: "btn btn-md btn-info my-2" %>  </td> 
    
        </tr>

app/views/services/_services-table.html.erb
<table class="table my-4">
    <thead>
      <tr class="text-center">
        <th scope="col"></th>
        <th scope="col">Titulo</th>
        <th scope="col">Estimativa</th>
        <th scope="col">Veiculo</th>
        <th scope="col">Cliente</th>
        <th scope="col">Mão de Obra</th>
        <th scope="col">Valor do Orçamento</th>
        <th scope="col">Valor Total</th>
        <th scope="col">Orçamento </th>
        <th scope="col">PDF</th>
        <th scope="col">Ações</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>

app/views/services/edit.html.erb
 <div class="container mx-auto pt-5 mt-5 w-50">
        <h2 class="text-center mb-4">Edite o serviço</h2>
        <%= render "form", service: @service %>
 </div>

app/views/services/index.html.erb
  <div class="container mx-auto w-50 text-center pt-5">
        <h2 class="display-4 font-italic">Todos os Serviços</h1>
        <div class="card w-56 border border-primary text-center mx-auto mt-5"> 
                <div class="card-body">
                    <div class="card-title">
                        Cadastre um novo serviço
                    </div>
                    <%= link_to "Clique aqui", new_service_path, class: "btn btn-primary" %>
                </div>
            </div>
    </div>
        
    <div class="container mx-auto pt-5 mb-5">
        <h2 class="text-center p-2 mt-5"> Serviços pendentes </h2>
        <table>
            <tbody>
                <%= render "services-table" %>
                <% @services.each do |service| %>
                    <% if service.status == false %>
                        <%= render "services/service", service: service %>
                    <% end %>  
                <% end %>
            </tbody>
        </table>

        <h2 class="text-center p-2 mt-5"> Serviços finalizados</h2>
            <table>
                <tbody>
                <%= render "services-table" %>
                <% @services.each do |service| %>
                    <% if service.status == true %>
                       <%= render "services/service", service: service %>
                    <% end %>  
                <% end %>  
                </tbody>
            </table>    
        </div>

    

app/views/services/new.html.erb
 <div class="container mx-auto pt-5 mt-5 w-50">
        <h2 class="text-center mb-4">Cadastre um serviço</h2>
        <%= render "form", service: @service %>
 </div>

app/views/services/pdf.html.erb
<h1> Valor da mão de obra: <%= @service.value %> </h1>


<h2 class="text-center p-2"> Tarefas realizadas neste serviço: </h2>
  <table class="table">
    <thead> 
      <tr>
        <th scope="col"> # </th>
        <th scope="col"> Nome </th>
        <th scope="col"> Modelo  </th>
        <th scope="col"> Valor </th>
      </tr>
    </thead>
    <tbody>
      <% @service.tasks.each do |task| %>
        <tr>
        <% if task %>
          <td>
            <%= task.id %>
          </td>
          <td>
            <%= task.title %>
          </td>
          <td>
            <%= task.description %>
          </td>
          <td>
            <%= task.status %>
          </td>
          <td>
            <%= task.estimative %>
          </td>
          <td> 
            <%= task.finish_date %>
          </td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>


  

app/views/services/show.html.erb
<div class="container mx-auto w-50 text-center pt-5 mb-5" >
    <h1 class="display-4">Serviço: <%= @service.title %> </h1>
    <h1> Valor da mão de obra: <%= @service.value %> </h1>
    <h3 class="">  Veiculo: <%= @service.vehicle.model %> </h3>   
    <h3 class="">
        <% if @sale %>
            Venda associada: <%= link_to @sale.name, sale_path(@sale) %>
        <% end %>
    </h3> 
</div>

<div class="container mx-auto w-50 my-4">
 <% if @service.status == false%>
        <div class="container mx-auto text-center my-5">
            <%= link_to "Concluir serviço", finish_service_service_path(@service), class: "btn-lg btn-success text-center" %>
        </div>

        <div class="card w-56 border border-primary text-center mx-auto my-4"> 
                <div class="card-body">
                    <div class="card-title">
                        Cadastre uma nova tarefa
                    </div>
                    <%= link_to "Clique aqui", new_service_task_path(@service), class: "btn btn-primary" %>
                    </div>
            </div>
 <% end %>




 <% if flash[:notice] or @service.status %>
    <div class="container mx-auto w-75 text-center ">
            <div class="jumbotron mx-auto py-5 border border-primary">
                <h2 class="text-success"> Serviço concluido</h2>
                <% if flash[:notice] %>
                    <%= image_tag "technoviking.gif", class: "mb-4 border border-dark" %>                
                    <% else %>
                    <h2 class="text-success"> Baixe o pdf </h2>
                <% end %>
                
                <br>
                
                <% if @sale%>
                    <%= link_to sale_path(@sale, format: :pdf) do  %> 
                        <i class="bi bi-filetype-pdf " style="font-size: 40px"></i>
                    <% end %>
                
                <% else %>
                    <%= link_to service_path(@service, format: :pdf) do  %> 
                        <i class="bi bi-filetype-pdf  " style="font-size: 40px"> </i>
                    <% end %>
                <% end %>

            </div>
    </div>
 <% end %>

        

   <h2 class="text-center p-2 mt-5"> Tarefas Pendentes: </h2>
    <table>
        <tbody>
            <%= render "tasks/task-table" %>
                <% @service.tasks.each do |task| %>
                        <% if task.status == false %>
                            <%= render "tasks/task", task: task %>
                        <% end %>  
                <% end %>
         </tbody>
      </table>

    <h2 class="text-center p-2"> Tarefas Completas: </h2>
        <table>
        <tbody>
            <%= render "tasks/task-table" %>
                <% @service.tasks.each do |task| %>
                        <% if task.status == true %>
                            <%= render "tasks/task", task: task %>
                        <% end %>  
                <% end %>
         </tbody>
      </table>

     <div class="buttons">
        <a href="/services" class="btn btn-primary my-5"> Voltar </a>
     </div>
            
</div>