config/routes.rb
Rails.application.routes.draw do
  resources :providers
  devise_for :users
  devise_for :installs
  
  resources :sales do
   member do  
      get :finish_sale
      get :cancel_sale
   end
  end 

  resources :parts
  root "homepage#index"

  resources :vehicles
  post "/vehicles/new" => "vehicles#create"

  resources :clients
  post "/clients/new" => "clients#create"

  resources :services do
    resources :tasks do
    end
  end

  resources :tasks do
    member do
      get :finish_task
    end
  end

  resources :services do
    member do
      get :finish_service
    end
  end

  resources :dashboards
  get "/dashboards/report/client" => "dashboards#client_report", as: "client_report"
  get "/dashboards/report/vehicle" => "dashboards#vehicle_report", as: "vehicle_report"
  get "/dashboards/report/service" => "dashboards#service_report", as: "service_report"
  get "/dashboards/report/sale" => "dashboards#sale_report", as: "sale_report"
  get "/dashboards/report/user" => "dashboards#user_report", as: "user_report"
  get "/dashboards/report/part" => "dashboards#part_report", as: "part_report"
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  validates :comission_percentage, numericality: { less_than_or_equal_to: 100, only_integer: true }

  def self.comission
    return Dashboard.first.comission_percentage
  end

  def self.featured_user
    if Sale.count > 0 
      @all_ids = Sale.all.pluck :user_id
      @id_counter = Hash.new(0)
      
      @all_ids.each do |id|
          @id_counter[id] += 1
      end

      #order by count (reversed major to minor) then get the first entry
      #then get the id which is the first value in the entry [0] or first
      @featured_user_id = (@id_counter.sort_by { |id, count| -count }).first[0]
      @featured_user = User.find(@featured_user_id)

      return @featured_user
    end
  end

  def self.featured_vehicles
    @vehicles = Vehicle.all
    @featured_vehicles = []

    for vehicle in @vehicles
      if vehicle.services.count > 1
        @featured_vehicles.push vehicle
      end
    end

    return @featured_vehicles.first(10)
  end

  def self.loyal_clients
    @clients = Client.all
    @loyal_clients = []

    for client in @clients
      if client.loyal_client
        @loyal_clients.push client
      end
    end
    @loyal_clients_count = @loyal_clients.count
    return @loyal_clients
  end

  #Registered ThisMonth related methods
  def self.vehicles_registered_this_month
    Vehicle.from_this_month
  end

  def self.clients_registered_this_month
    Client.from_this_month.limit(10).reverse()
  end

  def self.total_sales_this_month
    @sales = Sale.from_this_month
    @total = 0

    for sale in @sales
      @total += sale.value
    end

    return @total
  end

  def self.comission_value_this_month
    @sales = Sale.from_this_month
    @total = 0

    for sale in @sales
      @total += sale.comission_value
    end

    return @total
  end

  def self.sale_value_this_month
    Sale.from_this_month
  end

  #On-Time or Overdue related methods
  def self.services_done_on_time
    @on_time = Service.where("finish_date <= estimative")
  end

  def self.services_overdue
    @overdue = Service.where("finish_date > estimative ")
  end

  #Quantity helper methods
  def self.vehicle_quantity
    @vehicle_quantity = Vehicle.count
  end

  def self.service_quantity
    @service_quantity = Service.count
  end

  def self.client_quantity
    @client_quantity = Client.count
  end

  def self.task_quantity
    @task_quantity = Task.count
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_helper_dates

  def set_helper_dates
    @month_first_day = DateTime.now.to_date.beginning_of_month
    @month_last_day = DateTime.now.to_date.end_of_month
  end

  def index
    @dashboard = Dashboard.first
    @vehicles = Vehicle.last(5).reverse
    @services = Service.last(5).reverse
    @clients = Client.all
    @clients_recent = Client.last(5).reverse

    @sale_value_this_month = Dashboard.comission_value_this_month
    @total_sales_this_month = Dashboard.total_sales_this_month
    @overdue_services = Dashboard.services_overdue.count
  end

  def client_report
    @clients = Client.all
    @clients_by_sale_total = Client.clients_by_sale

    @clients_by_sale =
      Kaminari.paginate_array(@clients_by_sale_total)
        .page(params[:page]).per(5)

    @clients_this_month = Dashboard.clients_registered_this_month
    @loyal_clients = Dashboard.loyal_clients
    @loyal_clients_count = @loyal_clients.count
  end

  def vehicle_report
    @vehicles = Vehicle.all
    @vehicles_this_month = Dashboard.vehicles_registered_this_month
    @featured_vehicles = Dashboard.featured_vehicles
  end

  def service_report
    @services = Service.all
    @overdue_services = Dashboard.services_overdue
    @on_time_services = Dashboard.services_done_on_time
  end

  def part_report
    @part_by_sale = Part.parts_by_sale_amount
  end

  def sale_report
    @sales = Sale.all
    @sale_value_by_period = Sale.value_by_period(
      params[:start_date], params[:end_date]
    )
    @sale_by_period = Sale.sale_by_period(params[:start_date], params[:end_date])
  end


  def user_report
    @users = User.all
    @users_by_sale_value = User.users_by_sale_value
    @users_by_sale = User.users_by_sale
    return @users_by_sale ? @users_by_sale.length > 1 : [@users_by_sale]
  end

  def edit
    @dashboard = Dashboard.first
  end

  def show
    @comission_raw = Dashboard.first.comission_percentage
    @comission = @comission_raw / 100.0
    @dashboard = Dashboard.first
  end

  def update
    @dashboard = Dashboard.first

    if @dashboard.update(dashboard_params)
      redirect_to @dashboard
    else
      render :edit
    end
  end

  private

  def dashboard_params
    params.require(:dashboard).permit(:comission_percentage)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboards/_featured.html.erb
<div class="row my-4">
                    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
                        <div class="card text-center">
                            <h5 class="card-header" style="font-size: 18px">Valor Total de Orçamentos deste mes </h5>
                            <div class="card-body">
                              <h5 class="card-title"> R$ <%= @total_sales_this_month %></h5>
                              <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
                            </div>
                          </div>
                    </div>
                    
                    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
                        <div class="card text-center">
                            <h5 class="card-header"  style="font-size: 18px"> Comissao em Orçamentos deste mes</h5>
                            <div class="card-body">
                              <h5 class="card-title"> R$ <%= @sale_value_this_month %></h5>
                              <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
                            </div>
                          </div>
                    </div>
                    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
                        <div class="card text-center">
                            <h5 class="card-header"> Funcionario Destaque  </h5>
                            <div class="card-body">
                              <h5 class="card-title"><%= Dashboard.featured_user ? Dashboard.featured_user.name : 'Nenhum' %></h5>
                              <h5 > <%= Dashboard.featured_user ? Dashboard.featured_user.sales.count : 0 %> </h5>
                              <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
                            </div>
                        </div>
                    </div>
                </div>

<div class='row my-4'>
                    <div class="col-12 col-md-12 mb-4 align-items-center">
                        <div class="card text-center w-75 border border-danger">
                            <h5 class="card-header border border-danger" style="font-size: 18px"> Porcentagem da Comissão de Orçamento </h5>
                            <div class="card-body">
                              <h5 class="card-title fw-bold"> <%= Dashboard.comission %> % </h5>
                              <a class='btn btn-danger' href='/dashboards/1'> Configurar  </a>
                            </div>
                          </div>
                    </div>
</div>

app/views/dashboards/_part-featured.erb
<div class="row my-4">
  <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0d">
    <div class="card text-center">
      <h5 class="card-header" style="font-size: 18px">Total de Fornecedores </h5>
      <div class="card-body">
        <h5 class="card-title"> <%= Provider.all.count %> </h5>
        <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
      </div>
    </div>
  </div>
  </div>

app/views/dashboards/_recent-services.html.erb
<div class="col-12 col-xl-8 mb-4 mb-lg-0">
    <div class="card">
        <h5 class="card-header">Ultimos serviços cadastrados</h5>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Serviço</th>
                        <th scope="col">Veiculo</th>
                        <th scope="col">Valor</th>
                        <th scope="col">Data</th>
                        <th scope="col"></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @services.each do |service| %>
                        <tr>
                            <th scope="row"> <%= service.id %></th>
                            <td><%= service.title%></td>
                            <td><%= service.vehicle.model %> </td>
                            <td><%= service.value %></td>
                            <td><%= service.created_at.to_date %></td>
                            <td> <%= link_to "Ver", service, class: "btn btn-primary" %> </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
            </div>
                  <a href="/services" class="btn btn-block btn-primary">Ver todos</a>

            </div>
            </div>
        </div>

app/views/dashboards/_service-featured.html.erb
<div class="row my-4">
    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
        <div class="card text-center">
            <h5 class="card-header" style="font-size: 18px">Todos os serviços cadastrados </h5>
            <div class="card-body">
                <h5 class="card-title"><%= @services.count %></h5>
                <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
            </div>
            </div>
    </div>
    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
        <div class="card text-center">
            <h5 class="card-header" style="font-size: 18px">Serviços concluidos no prazo</h5>
            <div class="card-body">
                <h5 class="card-title"> <%= @on_time_services.count %></h5>
                <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
            </div>
            </div>
    </div>
    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
        <div class="card text-center">
            <h5 class="card-header"  style="font-size: 18px">Serviços concluidos fora do prazo</h5>
            <div class="card-body">
                <h5 class="card-title"><%= @overdue_services.count %></h5>
                <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
            </div>
            </div>
    </div>
    
</div>

app/views/dashboards/_side-panel.html.erb
<div class="container-fluid ">
    <div class="row flex-nowrap">
        <div class="col-auto  col-xl-3 px-sm-2 px-0 bg-light border border-black">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-5 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="#" class=" align-middle px-0">
                            <i class="fs-4 bi-house"></i> <%= link_to "Dashboard", dashboards_path %>
                        </a>
                    </li>
                    <li>
                        <a href="#submenu1" data-bs-toggle="collapse" class=" px-0 align-middle">
                            <i class="fs-4 bi-people-fill"></i> <span class="ms-1 d-none d-sm-inline">  <%= link_to "Clientes", client_report_path %> </span>
                        </a></span> </a>
                        
                    </li>
                    <li>
                        <a href="#" class=" px-0 align-middle">
                            <i class="fs-4 bi-minecart"></i> <span class="ms-1 d-none d-sm-inline"><%= link_to "Veiculos", vehicle_report_path %> </span></a>
                    </li>
                    <li>
                        <a href="#submenu2" data-bs-toggle="collapse" class=" px-0 align-middle ">
                            <i class="fs-4 bi-hammer"></i> <span class="ms-1 d-none d-sm-inline">  <%= link_to "Serviços", service_report_path %> </span></a>
                    </li>
                    
                    <li>
                        <a href="#" class=" px-0 align-middle">
                            <i class="fs-4 bi-receipt"></i> <span class="ms-1 d-none d-sm-inline"> 
                            <%= link_to "Orçamentos", sale_report_path %>
                            </span> </a>
                    </li>

                       
                    <li>
                        <a href="#" class=" px-0 align-middle">
                            <i class="fs-4 bi bi-person-workspace"></i> <span class="ms-1 d-none d-sm-inline"> 
                            <%= link_to "Funcionários", user_report_path %>
                            </span> </a>
                    </li>

                    <li>
                        <a href="#" class=" px-0 align-middle">
                            <i class="fs-4 bi bi-box-seam"></i> <span class="ms-1 d-none d-sm-inline"> 
                            <%= link_to "Peças", part_report_path %>
                            </span> </a>
                    </li>

                    <li>
                        <a href="#" class=" px-0 align-middle">
                            <i class="fs-4 bi-gear-fill"></i><span class="ms-1 d-none d-sm-inline">  <%= link_to "Configuraçoes", dashboard_path(Dashboard.first) %></span> </a>
                    </li>
                        </ul>
                <hr>
            </div>
        </div>

app/views/dashboards/_user-featured.html.erb
<div class="row my-4">
  <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0d">
    <div class="card text-center">
      <h5 class="card-header" style="font-size: 18px">Funcionario destaque </h5>
      <div class="card-body">
        <h5 class="card-title"><%= Dashboard.featured_user ? Dashboard.featured_user.name : "Nenhum" %></h5>
        <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
      </div>
    </div>
  </div>

  </div>

app/views/dashboards/_user_by_sale.html.erb
<div class="col-12 col-md-12 mb-4 align-items-center">
    <div class="card w-75">
        <h5 class="card-header text-primary"> Funcionários por Orçamentos Realizados </h5>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Nome</th>
                        <th scope="col">Função</th></th>
                        <th scope="col">Quantia de Orçamentos</th>
                        <th scope="col">Data de cadastro</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users_by_sale.each do |user| %>
                        <tr>
                            <th scope="row"> <%= user.id %></th>
                            <td><%= user.name %></td>
                            <td><%= user.parsed_role %> </td>
                            <td><%= user.sales.count %></td>
                            <td><%= user.created_at_normalized %></td>
                        </tr>
                        <% end %>
                    </tbody>
                    </table>
            </div>
                   
            </div>
            </div>
    </div>

app/views/dashboards/_vehicle-featured.html.erb
<div class="row">
                    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0d">
                        <div class="card text-center">
                            <h5 class="card-header" style="font-size: 18px">Veiculos cadastrados neste mes </h5>
                            <div class="card-body">
                              <h5 class="card-title"><%= @vehicles_this_month.count %></h5>
                              <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
                            </div>
                          </div>
                    </div>
                    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
                        <div class="card text-center">
                            <h5 class="card-header" style="font-size: 18px">Veiculos destaque</h5>
                            <div class="card-body">
                              <h5 class="card-title"><%= @featured_vehicles.count %> </h5>
                              <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
                            </div>
                          </div>
                    </div>
                    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
                        <div class="card text-center">
                            <h5 class="card-header"  style="font-size: 18px">Veiculos totais</h5>
                            <div class="card-body">
                              <h5 class="card-title"> <%= @vehicles.count %> </h5>
                              <p class="card-text fw-bold"><%= @month_first_day %> -- <%= @month_last_day %></p>
                            </div>
                          </div>
                    </div>
                </div>

app/views/dashboards/_vehicles_registered_this_month.html.erb
                    <div class="col-12 col-xl-8 mb-4 mb-lg-0">
                        <div class="card">
                            <h5 class="card-header text-primary">Veiculos registrados este mes</h5>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                          <tr>
                                            <th scope="col">Id</th>
                                            <th scope="col">Modelo</th>
                                            <th scope="col">Placa</th></th>
                                            <th scope="col">Cliente</th>
                                            <th scope="col">Data</th>
                                            <th scope="col"></th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                         <% @vehicles_this_month.each do |vehicle| %>
                                            <tr>
                                                <th scope="row"> <%= vehicle.id %></th>
                                                <td><%= vehicle.model%></td>
                                                <td><%= vehicle.registration_plate %> </td>
                                                <td><%= vehicle.client.name %></td>
                                                <td><%= vehicle.created_at.to_date %></td>
                                                <td> <%= link_to "Ver", vehicle, class: "btn btn-primary" %> </td>
                                            </tr>
                                          <% end %>
                                        </tbody>
                                      </table>
                                </div>
                                   
                                </div>
                                </div>
                            </div>

app/views/dashboards/edit.html.erb
<%= render "side-panel" %>
<main class="container">
  <h1> Alterar Configuração de Porcentagem da Comissão</h1>

  <%= simple_form_for @dashboard do |f| %>
    <%= f.input :comission_percentage, value: "Comissão" %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

</main>

app/views/dashboards/index.html.erb
<%= render "side-panel"%>

<div class="container my-5">
  <h2>Dashboard Geral</h2>
  <p>Nesta página você poderá inspecionar alguns dados administrativos gerais </p>
  <%= render 'featured' %>
  <div class="row my-5">
    <%= render "recent-services" %>
  </div>
  <div class="row my-5">
    <%= render "recent-vehicles" %>
  </div>
  <div class="row my-5">
    <%= render "recent_clients" %>
  </div>
</div>
</div>
</div>

app/views/dashboards/part_report.html.erb
<%= render "side-panel"%>

  <main class="container">
                <h1 class="h2">Relatórios de Peças </h1>
                <p>  </p>
                    <%= render "part-featured"%>
                <div class="row my-5">
                    <%= render "part_by_sale" %>
                </div>
            </main>
        </div>
    </div>

app/views/dashboards/service_report.html.erb
<%= render "side-panel"%>

  <main class="container">
                <h1 class="h2">Relatórios de Serviços</h1>
                <p>Nesta página você poderá inspecionar dados relacionados a serviços </p>
                <%= render 'service-featured' %>
                <div class="row mb-5">
                    <%= render 'on_time_services' %>
                </div>
                <div class="row my-5">
                    <%= render 'overdue_services' %>
                </div>
                <div class="row my-5">

                </div>
            </main>
        </div>
    </div>

app/views/dashboards/user_report.html.erb
<%= render "side-panel"%>

  <main class="container">
                <h1 class="h2"> Relatórios de Funcionários </h1>
                <p> Nesta página você poderá inspecionar dados relacionados a orçamentos </p>
                <div class="row mb-5">
                <%= render 'user-featured' %>
               </div>

               <div class="row mb-5">
                    <%= render 'user_by_sale' %>
                </div>

                <div class="row my-5">

                <div class="col-12 col-md-12 mb-4 align-items-center">
                    <div class="card w-75">
                        <h5 class="card-header text-primary"> Funcionários por Valor de Orçamento realizado </h5>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                        <th scope="col">Id</th>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Função</th></th>
                                        <th scope="col">Valor somado dos Orçamentos</th>
                                        <th scope="col">Data de cadastro</th>
                                        <th scope="col"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @users_by_sale_value.each do |user| %>
                                            <tr>
                                                <th scope="row"> <%= user.id %></th>
                                                <td><%= user.name %></td>
                                                <td><%= user.parsed_role %> </td>
                                                <td><%= user.sales.sum("value") %></td>
                                                <td><%= user.created_at_normalized %></td>
                                            </tr>
                                        <% end %>
                                    </tbody>
                                    </table>
                            </div>
                                
                            </div>
                            </div>
                    </div>











                </div>
            </main>
        </div>
    </div>