config/routes.rb
Rails.application.routes.draw do
  resources :providers
  devise_for :users
  devise_for :installs
  
  resources :sales do
   member do  
      get :finish_sale
      get :cancel_sale
   end
  end 

  resources :parts
  root "homepage#index"

  resources :vehicles
  post "/vehicles/new" => "vehicles#create"

  resources :clients
  post "/clients/new" => "clients#create"

  resources :services do
    resources :tasks do
    end
  end

  resources :tasks do
    member do
      get :finish_task
    end
  end

  resources :services do
    member do
      get :finish_service
    end
  end

  resources :dashboards
  get "/dashboards/report/client" => "dashboards#client_report", as: "client_report"
  get "/dashboards/report/vehicle" => "dashboards#vehicle_report", as: "vehicle_report"
  get "/dashboards/report/service" => "dashboards#service_report", as: "service_report"
  get "/dashboards/report/sale" => "dashboards#sale_report", as: "sale_report"
  get "/dashboards/report/user" => "dashboards#user_report", as: "user_report"
  get "/dashboards/report/part" => "dashboards#part_report", as: "part_report"
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :client
  has_many :services, dependent: :destroy
  scope :from_this_month, lambda {
    where("vehicles.created_at > ? AND vehicles.created_at < ?",
          Time.now.beginning_of_month, Time.now.end_of_month)
  }

  validates :model, presence: true
  validates :registration_plate, presence: true, uniqueness: true

  def self.search(search)
    if search
      @result = Vehicle.where("registration_plate LIKE ?", "%" + search + "%")
      return @result ? @result : Vehicle.all
    else
      return Vehicle.all
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles_raw =
      Vehicle.search(params[:search])

    @vehicles =
      Kaminari.paginate_array(@vehicles_raw).page(params[:page])
  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @services = @vehicle.services
  end

  def new
    @vehicle = Vehicle.new
    @clients = Client.all
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to action: "index"
    else
      render :new
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
    @clients = Client.all
  end

  def update
    @vehicle = Vehicle.find(params[:id])

    if @vehicle.update(vehicle_params)
      redirect_to action: "index"
    else
      redirect_to action: "edit"
    end
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    redirect_to action: "index"
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:search, :id, :model, :registration_plate, :client_id)
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
        <%= form_with model: vehicle do |form|%>            
            <div class="form-group pt-2">
                <%= form.label :model, value: "Modelo:" %> 
                <%= form.text_field :model, {class: "form-control", placeholder: "Digite o modelo do carro"} %>
            </div>
            <div class="form-group pt-2">
                <%= form.label :registration_plate, value: "Placa:" %> 
                <%= form.text_field :registration_plate, {class: "form-control", placeholder: "Escreva a placa", id: "registration_plate"} %>
            </div>
            <div class="form-group pt-2">
                <label for="client_id"> Escolha um cliente </label> <br>
                <%= form.select :client_id, @clients.collect{ |c| [c.name, c.id] }, {},  prompt: "Escolha um Cliente", class: "form form-group form-control" %>
            </div>

            <div class="lead pt-5">
                <%= form.submit "Concluir", class: "btn btn-primary" %>
            </div>
         <% end %>


        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.7/jquery.inputmask.min.js" integrity="sha512-jTgBq4+dMYh73dquskmUFEgMY5mptcbqSw2rmhOZZSJjZbD2wMt0H5nhqWtleVkyBEjmzid5nyERPSNBafG4GQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
         <script>
            $(document).ready(function(){
            $("#registration_plate").inputmask({mask: '***-****'});
            });
         </script>
  

app/views/vehicles/edit.html.erb
 <div class="container mx-auto pt-5 mt-5 w-50">
        <h2 class="">Edite o veiculo</h2>
        <%= render "form", vehicle: @vehicle %>
 </div>

app/views/vehicles/index.html.erb
<style>
    .row {
        text-align: center;
        margin: 0 auto;
    }

    .row .col-lg-4 {
        display: inline-block;
        vertical-align: middle;
        float: none;
    }
</style>



<div class="container mx-auto w-50 text-center">
    <div class="card w-56 border border-primary text-center mx-auto mt-5">
        <div class="card-body">
            <div class="card-title">
                Cadastre um novo veículo
            </div>
            <%= link_to "Clique aqui", new_vehicle_path, class: "btn btn-primary" %>
        </div>
    </div>
</div>

<h1> Veiculos </h1>
    <div class="text-end ">
        <%= form_tag(vehicles_path, method: :get) do %>
            <%= text_field_tag(:search, params[:search]) %>
            <%= submit_tag ("Pesquisar") %>
        <% end %>
    </div>
 
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Placa </th>
    </tr>
  </thead>
  <tbody>
    
    <% @vehicles.each do |vehicle| %>    
        <tr>
        <td> <%= vehicle.id %> </td>
        <td> <%= link_to vehicle.model, vehicle %></td>
        <td> <%= vehicle.registration_plate %> </td>
        </tr>
    <% end %>
    </tbody>
    </table>
        <div class="digg_pagination text-center mt-4">
            <%= paginate @vehicles %>

        </div>
    </div>

app/views/vehicles/new.html.erb
 <div class="container mx-auto pt-5 mt-5 w-50">
        <h2 class="">Cadastre um novo veiculo</h2>
        <%= render "form", vehicle: @vehicle %>
 </div>

app/views/vehicles/show.html.erb
<div class="container mx-auto">
    <div class="jumbotron ">
        <h1 class="text-center display-4 font-weight-bold"> Veículo: <%= @vehicle.model %> </h1>
        <div class="row my-5 ">
            <div class="col-6">
                <ul class="">
                <li class="" >
                    <i class="bi bi-person-badge mr-3 mt-2" style="font-size: 40px"></i>
                    <span class="font-italic h2" > Dono do Veículo: 
                        <span class="text-primary"> <%= link_to @vehicle.client.name, @vehicle.client%> </span>
                    </span>
                </li>
                <li class="" >
                    <i class="bi bi-telephone mr-3 mt-2" style="font-size: 40px"></i>            
                    <span class="font-italic h2" > Telefone do dono do Veículo: 
                        <span class="text-primary"> <%= @vehicle.client.phone %>  </span>
                    </span>
                </li>
                
                </ul>
            </div>

            <div class="col-6">
                <ul> 
                <li class="" >
                    <i class="fa fa-car mr-3 mt-2" style="font-size: 40px"></i>            
                    <span class="font-italic h2" > Placa do Veículo: 
                        <span class="text-primary"> <%= @vehicle.registration_plate %>  </span>
                    </span>
                </li>
                <li class="">
                    <i class="fa fa-calendar mr-3 mt-2" style="font-size: 40px"></i>
                    <span class=" font-italic h2"> Data do cadastro: 
                        <span class="text-primary"> <%= @vehicle.created_at.to_date.to_s %>  </span>
                    </span>
                </li>
                
                </ul>
            </div>
        </div>

        <div class="services text-center">
            <button class="btn btn-primary btn-lg" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Serviços para este veiculo
            </button>
        
            <div class="collapse" id="collapseExample">
            <div class="card card-body">
                <ul class="list-group">   
                    <% @services.each do |service| %>
                        <li class="list-group-item fw-bold"> 
                            <%= link_to service.title, service%>
                        </li>
                    <% end %>
                </ul>
            </div>
            </div>
        </div>


        <div class="row my-5 text-center">
            <div class="col-12">
                 <%= link_to 'Voltar', url_for(:back), class: "btn btn-lg btn-info my-2 mr-5" %> 
                 <%= link_to "Editar", edit_vehicle_path(@vehicle), class: "btn btn-lg btn-warning my-2 mr-5" %>
                 <%= link_to "Deletar", vehicle_path(@vehicle), class: "btn btn-lg btn-danger my-2 mr-5", 
                                                                      method: :delete, 
                                                                      data: { confirm: "Tem certeza que deseja deletar o veiculo " + @vehicle.model + " ?"}  %>
            </div>
        </div>
    
    </div>
</div>