config/routes.rb
Rails.application.routes.draw do
  resources :providers
  devise_for :users
  devise_for :installs
  
  resources :sales do
   member do  
      get :finish_sale
      get :cancel_sale
   end
  end 

  resources :parts
  root "homepage#index"

  resources :vehicles
  post "/vehicles/new" => "vehicles#create"

  resources :clients
  post "/clients/new" => "clients#create"

  resources :services do
    resources :tasks do
    end
  end

  resources :tasks do
    member do
      get :finish_task
    end
  end

  resources :services do
    member do
      get :finish_service
    end
  end

  resources :dashboards
  get "/dashboards/report/client" => "dashboards#client_report", as: "client_report"
  get "/dashboards/report/vehicle" => "dashboards#vehicle_report", as: "vehicle_report"
  get "/dashboards/report/service" => "dashboards#service_report", as: "service_report"
  get "/dashboards/report/sale" => "dashboards#sale_report", as: "sale_report"
  get "/dashboards/report/user" => "dashboards#user_report", as: "user_report"
  get "/dashboards/report/part" => "dashboards#part_report", as: "part_report"
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :parts, dependent: :destroy
  #get all parts where has_sale, get their user id
  def self.provider_by_part
    @parts = []
    Part.all.each do |part| 
      if part.has_sale
        @parts.append(part)
      end 
    end 
    
    return @parts
  end

  def self.search(search)
    if search 
        @result = Provider.where("cnpj LIKE ?", "%" + search + "%")
        puts(@result, "here")
        return @result ? @result : Provider.all
    else 
        return Provider.all 
    end  
  end 
end

app/models/sale.rb
require "time"
require "date"

class Sale < ApplicationRecord
  has_many :sale_part
  has_many :parts, through: :sale_part

  belongs_to :client, optional: true
  belongs_to :service, optional: true
  belongs_to :user

  after_initialize :set_defaults
  after_initialize :received_part_ids
  after_initialize :received_relation_with_parent_model
  after_initialize :synchronize_total_value
  after_initialize :calculate_comission
  before_save :infer_sale_name
  scope :from_this_month, lambda {
    where("sales.created_at > ? AND sales.created_at < ?",
          Time.now.beginning_of_month, Time.now.end_of_month)
  }

  def set_defaults
    self.value ||= 0.0
    self.finished ||= false
  end

  def calculate_comission
    if !self.finished
      comission_percentage = Dashboard.comission ? Dashboard.comission : 0.0
      self.comission_value = comission_percentage / 100.0 * self.value
      self.save
    end
  end

  def synchronize_total_value
    if self.parts.count > 0
      self.value = SaleValueUpdater.calculate_total_value(self)
    end
  end

  def received_part_ids
    if self.part_ids
      self.part_ids << Part.where(id: [part_ids])
    end
  end

  def received_relation_with_parent_model
    if self.service_id != "Selecione" && self.service_id
      self.service = Service.find(service_id)
    elsif self.client_id != "Selecione" && self.client_id
      self.client = Client.find(client_id)
    end
  end

  def infer_sale_name
    @date = Date.today
    @sale_for_who = self.client ? self.client.name : self.service.title
    self.name = "Orçamento para " + @sale_for_who + " - " + @date.to_s
  end

  def get_total_value
    @total_value = self.comission_value + self.value + (self.service ? self.service.value : 0)

    return @total_value
  end

  def parsed_finished
    case self.finished
    when nil
      "Cancelado a pedido do cliente"
    when true
      "Orçamento Aprovado"
    when false
      "Orçamento ainda não Aprovado"
    end
  end

  def created_at_normalized
    return Date.parse(self.created_at.to_s)
  end

  def self.finish_sale(sale)
    return sale.update(finished: true) ? true : false
  end

  def cancel_sale
    return self.update(finished: nil) ? true : false
  end

  def self.value_by_period(start_date, end_date)
    if start_date && end_date
      @sales = Sale.where(:created_at => start_date..end_date)
      return @sales.sum("comission_value")
    else
      return 0
    end
  end

  def self.sale_by_period(start_date, end_date)
    if start_date && end_date
      @sales = Sale.where(:created_at => start_date..end_date)
      return @sales
    end
  end


end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales or /sales.json
  def index
    respond_to do |format|
      format.html 
      format.json { render json: SaleDatatable.new(params) }
    end 
  end

  # GET /sales/1 or /sales/1.json
  def show
    respond_to do |format|
        format.html
        format.pdf do
            render pdf: "Invoice No. ",
            page_size: 'A4',
            template: "sales/pdf.html.erb",
            layout: "pdf.html.erb",
            orientation: "Landscape",
            lowquality: true,
            zoom: 1,
            dpi: 75
        end
    end
end

  # GET /sales/new
  def new
    @sale = Sale.new
    @parts = Part.all
  end

  # GET /sales/1/edit
  def edit
    @edit = true
    @parts = Part.all
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)
    @user = current_user
    @sale.user_id = @user.id 
    respond_to do |format|
      if @sale.save
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sale_url(@sale), notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Orçamento deletado." }
      format.json { head :no_content }
    end
  end

  def finish_sale
        @sale = Sale.find(params[:id])
        @result = Sale.finish_sale(@sale)
        if @result 
          flash[:notice] = "Orçamento aprovado e encerrado com sucesso!"
        else 
          flash[:notice] = "Falha na aprovação e encerramento, tente novamente."
        end
        redirect_to sale_path(@sale)
  end
  
  def cancel_sale
        @sale = Sale.find(params[:id])
        @result = @sale.cancel_sale
        if @result 
          flash[:notice] = "Orçamento cancelado e encerrado com sucesso!"
        else 
          flash[:notice] = "Falha no cancelamento e encerramento, tente novamente."
        end
        redirect_to sale_path(@sale)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:start_date, :end_date, :name, :description, :value, :comission_value, :service_id, :client_id, :user_id, part_ids: [])
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<% if !@sale.finished || current_user.role != 1 %>
  <%# <% if @sale.finished %>
    <%# <h1 class="text-danger"> Cuidado! Este orçamento ja foi aprovado e apenas você, administrador pode editar o mesmo</h1>  
  <% end %> 

  <%= form_with(model: sale) do |form| %>

  <div class="from-group pt-2">
    <%= form.label :description, value: "Descrição do orçamento" %>
    <%= form.text_field :description, {class: "form-control", placeholder: ""} %>
  </div>

  <div class="from-group pt-2">
    <h2> Valor da comissão configurado: <strong> <%= Dashboard.comission  %> % </strong> </h2>
  </div>

  <% if !@edit %>
    <div class="container border rounded border-dark mt-3">
      <p class="form-group pt-2"> Este orçamento pertence a um cliente ou serviço? </p>
      <div class="form-check">
        <input onchange="validateVisibility()" class="form-check-input" type="checkbox" value="Cliente" id="client">
        <label class="form-check-label" for="client">
          Cliente
        </label>
      </div>
      <div class="form-check">
        <input onchange="validateVisibility()" class="form-check-input" type="checkbox" value="Serviço" id="service">
        <label class="form-check-label" for="service">
          Serviço
        </label>
      </div>

      <div class="form-group pt-2" id="client_form" style="visibility: hidden">
        <%= form.label :client_id, value: "Cliente" %>
        <%= form.select(:client_id, Client.all.collect {|p| [ p.name, p.id ] }, 
                                                      { :prompt => "Selecione"}, 
                                                      { :multiple => false, :size => 1, :class => "form-select" }) %>
      </div>

      <label for=""> Serviço:</label>
      <div class="form-group pt-2" id="service_form" style="visibility: hidden">
        <%= form.select(:service_id, Service.all.collect {|p| [ p.title, p.id ] }, 
                                                      { :prompt => "Selecione"},
                                                      { :multiple => false, :size => 1, :class => "form-select" }) %>
      </div>
    </div>
  <% end %>

  <label for=""> Peças:</label>
  <div class="form-group py-2">
    <%= form.select(:part_ids, @parts.collect {|p| [ p.name + " -  R$ " + p.value.to_s + " - " + p.model ,  p.id ] }, 
                                                    { },
                                                    { :multiple => true,  :class => "form-select border border-dark p-5" }) %>
  </div>

  <div class="lead pt-5">
    <%= form.submit "Cadastrar", class: "btn btn-primary" %>
    <%= link_to 'Voltar', sales_path, class: "btn btn-primary" %>    

  </div>
  <% end %>

  <script>
    var serviceVisibility;
    var clientVisibility;
    var client = document.getElementById('client')
    var service = document.getElementById('service')
    $('select').selectpicker();
    function changeVisibility() {
      document.getElementById('service_form').style.visibility = serviceVisibility;
      document.getElementById('client_form').style.visibility = clientVisibility;
    }

    function validateVisibility() {
      if (service.checked == true && client.checked == true) {
        client.checked = false
        service.checked = false
        serviceVisibility = "hidden"
        clientVisibility = "hidden"
      } else if (client.checked == true) {
        serviceVisibility = "hidden"
        clientVisibility = "visible"
      } else if (service.checked == true) {
        serviceVisibility = "visible"
        clientVisibility = "hidden"
      } else {
        serviceVisibility = "hidden"
        clientVisibility = "hidden"
      }
      changeVisibility()

    }




</script>

<% else %>
  <h2> Orçamentos aprovados não podem ser editados. Contate o administrador </h2>
<% end %>

app/views/sales/edit.html.erb
<h1>Editar Orçamento</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>


    <div class="container mx-auto w-50 text-center">
        <div class="card w-56 border border-primary text-center mx-auto mt-5">
            <div class="card-body">
                <div class="card-title">
                    Cadastre um novo Orçamento
                </div>
                <%= link_to "Clique aqui", new_sale_path, class: "btn btn-primary" %>
            </div>
        </div>
    </div>

<h1>Orçamentos</h1>

<table id="sales-datatable" class="table table-striped table-bordered" style="width:100%" data-source="<%= sales_path(format: :json) %>">
  <thead>
    <tr>
      <th>ID</th>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Valor Total</th>
      <th>Data de Criação</th>
      <th>Aprovado</th>
      <th>Editar</th>
      <th>Deletar</th>
      <th>PDF</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>


<%= link_to "New Sale", new_sale_path %>


<script type="text/javascript">
  $(document).ready( function() {
           var jsondata;
           getdata();
           function getdata(){
              const getPeople = async () => {
               const data = await fetch('http://127.0.0.1:3000/sales.json', {
                  method: 'GET',
                  headers: {
                      'Content-Type': 'application/json',                                  
                  }
               });
               await initialiseTable()
               };
             getPeople();
           }

  });

      function initialiseTable(){
 
  $('#sales-datatable').dataTable({
      "language": { url: "https://cdn.datatables.net/plug-ins/1.12.1/i18n/pt-BR.json" } ,
      "processing": true,
      "serverSide": true,
      "bDestroy": true,
      "ajax": {
      "url": $('#sales-datatable').data('source')
      },
      "pagingType": "full_numbers",
      "columns": [
        {"data": "id"},
        {"data": "name"},
        {"data": "description"},
        {"data": "value"},
        {"data": "created_at"},
        {"data": "finished"},
        {"data": "edit"},
        {"data": "delete"},
        {"data": "pdf"},

      ]
    });
      }

</script>

app/views/sales/new.html.erb
<div class="container mx-auto pt-5 mt-5 w-50">
    <h2 class="text-center mb-5"> Novo Orçamento </h2>

    <%= render 'form', sale: @sale %>
    
</div>

app/views/sales/pdf.html.erb
<p id="notice"><%= notice %></p>

<div class="container text-center mx-auto border border-dark" >
<% if !@sale.finished  %>
  <h3 style="color: red; text-align: center;"> ATENÇÃO ORÇAMENTO NÃO FINALIZADO POR NOSSO COLABORADOR 
  SUJEITO A ALTERAÇÕES ATÉ CONFIRMAÇÃO !</h3>
 
<% end %>


<p style="text-align: center">
  <strong class="text-danger" style="font-size: 40px"> Valor Total a Pagar: R$ <%= @sale.get_total_value %> </strong>
</p>


<p class="text-center">
  <strong class="text-primary"> Colaborador que efetuou o orçamento: </strong>
  <%= @sale.user.name %> <strong style="color: blue"> ID: <%= @sale.user.id %> </strong>
</p>
<p>
  <strong>Identificação Geral:</strong>
  <%= @sale.name %>
</p>
<p>
  <strong>Observações:</strong>
  <%= @sale.description %>
</p>

<% if @sale.service %>
 <p class="fw-bold">
    Valor da mão de obra (Serviço): 
    R$ <%= @sale.service.value %>
  </p>
<p> 
  <strong> Serviço associado ao orçamento:</strong>
  <%= link_to @sale.service.identification_string, service_path(@sale.service.id) %>
</p>
<% elsif @sale.client %>
<p> 
  <strong> Nome do cliente:</strong>
  <%= @sale.client.name %>
</p>
<% end %>


 <h2 class="text-center p-2"> Peças deste orçamento: </h2>
  <table class="table">
    <thead> 
      <tr>
        <th scope="col"> # </th>
        <th scope="col"> Nome </th>
        <th scope="col"> Modelo  </th>
        <th scope="col"> Valor </th>
      </tr>
    </thead>
    <tbody>
      <% @sale.parts.each do |part| %>
        <tr>
        <% if part %>

          <td>
            <%= part.id %>
          </td>
          <td>
            <%= link_to part.name %>
          </td>
          <td>
            <%= part.model %>
          </td>
          <td>
            <%= part.value %>
          </td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>





<% if @sale.service %>
  <h2 class="text-center py-5"> Tarefas realizadas no serviço deste orçamento: </h2>
    <table class="table">
      <thead> 
        <tr>
          <th scope="col"> # </th>
          <th scope="col"> Titulo </th>
          <th scope="col"> Descrição  </th>
        </tr>
      </thead>
      <tbody class="text-center">
        <% @sale.service.tasks.each do |part| %>
          <tr>
          <% if part %>
            <td>
              <%= part.id %>
            </td>
            <td>
              <%= part.title %>
            </td>
            <td>
              <%= part.description %>
            </td>
          <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container mx-auto text-center" >
  <h2 class="text-center my-4"> Visualizar <%= @sale.name %> </h2>

  <% if !@sale.finished %>
    <%= link_to "Aprovar orçamento", finish_sale_sale_path(@sale), class: "mb-4 btn-lg btn-success text-center" %>
  <% elsif @sale.finished == nil%>
    <h3> Orçamento cancelado a pedido do cliente.</h3>
  <% else %>
    <h3> Orçamento aprovado e finalizado </h3>
  <% end %>


  <p class="mt-4">
    <strong> Feito por: </strong>
    <%= @sale.user.name %>
  </p>

  <p>
  <strong> Status do orçamento: </strong>
  <%= @sale.parsed_finished%>
  </p>
  <p>
    <strong>Nome:</strong>
    <%= @sale.name %>
  </p>
  <p>
    <strong>Descrição:</strong>
    <%= @sale.description %>
  </p>
  <p>
    <strong>Valor das peças:</strong>
    <%= @sale.value %>
  </p>

  <p> 
    <strong> Valor da Comissão: </strong>
    <%= @sale.comission_value %>
  </p>

  <% if @sale.service %>
    <p>
      Valor da mão de obra: 
      <%= @sale.service.value %>
    </p>
  <% end %>

  <% if @sale.service %>
  <p> 
    <strong> Serviço associado a venda:</strong>
    <%= link_to @sale.service.title, service_path(@sale.service.id) %>
  </p>
  <% elsif @sale.client %>
  <p> 
    <strong> Cliente associado a venda:</strong>
    <%= link_to @sale.client.name, client_path(@sale.client.id) %>
  </p>
  <% end %>

  <h2 class="text-center p-2"> Peças desta venda: </h2>
  <table class="table">
    <thead> 
      <tr>
        <th scope="col"> # </th>
        <th scope="col"> Nome </th>
        <th scope="col"> Modelo  </th>
        <th scope="col"> Valor </th>
      </tr>
    </thead>
    <tbody>
      <% @sale.parts.each do |part| %>
        <tr>
        <% if part %>

          <td>
            <%= part.id %>
          </td>
          <td>
            <%= link_to part.name, part_path(part) %>
          </td>
          <td>
            <%= part.model %>
          </td>
          <td>
            <%= part.value %>
          </td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    <strong class="display-4 text-danger"> Valor total: <%= @sale.get_total_value() %> </strong>
  </p>

  <%= link_to sale_path(@sale, format: :pdf) do  %> 
    <i class="bi bi-filetype-pdf " style="font-size: 40px"></i>
  <% end %> |
  <%= link_to "Deletar", sale_path(@sale), method: :delete%> |
  <%= link_to 'Editar', edit_sale_path(@sale) %> |
  <%= link_to 'Voltar', sales_path %> |
</div>